//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurskaia_Tarasiuk_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtPerYear
    {
        public int id { get; set; }
        public Nullable<int> national_debt_id { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<decimal> debt { get; set; }
    
        public virtual NationalDebt NationalDebt { get; set; }
        public virtual Year Year { get; set; }
    }
}
