//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurskaia_Tarasiuk_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suicide
    {
        public int id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> age_id { get; set; }
        public Nullable<int> generation_id { get; set; }
        public Nullable<int> sex_id { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<int> suicide_count { get; set; }
        public Nullable<int> population { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual Country Country { get; set; }
        public virtual Generation Generation { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual Year Year { get; set; }
    }
}
